### ISSUE TITLE
error 好像和quickshop冲突了，但是我以前正常的。。。

### ISSUE THREAD

**Issue by 404forever1** [blank038/ServerMarket#11]
[00:45:01 ERROR]: Error occurred while enabling ServerMarket v2.6.0 (Is it up to date?)
java.lang.LinkageError: loader constraint violation: when resolving method 'void com.zaxxer.hikari.HikariDataSource.<init>(com.zaxxer.hikari
.HikariConfig)' the class loader 'AyCore-1.0.6-BETA.jar' @59b92f19 of the current class, com/aystudio/core/bukkit/util/mysql/interfaces/impl
/HikariDataSourceHandler, and the class loader 'QuickShop-Hikari-5.2.0.14.jar' @6e8820af for the method's defining class, com/zaxxer/hikari/
HikariDataSource, have different Class objects for the type com/zaxxer/hikari/HikariConfig used in the signature (com.aystudio.core.bukkit.u
til.mysql.interfaces.impl.HikariDataSourceHandler is in unnamed module of loader 'AyCore-1.0.6-BETA.jar' @59b92f19, parent loader java.net.U
RLClassLoader @7de26db8; com.zaxxer.hikari.HikariDataSource is in unnamed module of loader 'QuickShop-Hikari-5.2.0.14.jar' @6e8820af, parent
 loader java.net.URLClassLoader @7de26db8)
        at AyCore-1.0.6-BETA.jar/com.aystudio.core.bukkit.util.mysql.interfaces.impl.HikariDataSourceHandler.<init>(HikariDataSourceHandler.
java:33) ~[AyCore-1.0.6-BETA.jar:?]
        at AyCore-1.0.6-BETA.jar/com.aystudio.core.bukkit.util.mysql.MySqlStorageHandler.<init>(MySqlStorageHandler.java:30) ~[AyCore-1.0.6-
BETA.jar:?]
        at ServerMarket-2.6.0.jar/com.blank038.servermarket.dto.impl.MysqlStorageHandlerImpl.initialize(MysqlStorageHandlerImpl.java:58) ~[S
erverMarket-2.6.0.jar:?]
        at ServerMarket-2.6.0.jar/com.blank038.servermarket.dto.AbstractStorageHandler.check(AbstractStorageHandler.java:41) ~[ServerMarket-
2.6.0.jar:?]
        at ServerMarket-2.6.0.jar/com.blank038.servermarket.internal.plugin.ServerMarket.loadConfig(ServerMarket.java:87) ~[ServerMarket-2.6
.0.jar:?]
        at ServerMarket-2.6.0.jar/com.blank038.servermarket.internal.plugin.ServerMarket.onEnable(ServerMarket.java:45) ~[ServerMarket-2.6.0
.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[leaf-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[leaf-1.20.4.jar:gi
t-Leaf-"3669cb6"]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at PlugManX.jar/com.rylinaux.plugman.util.PaperPluginUtil.load(PaperPluginUtil.java:421) ~[PlugManX.jar:?]
        at PlugManX.jar/com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:116) ~[PlugManX.jar:?]
        at PlugManX.jar/com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:97) ~[PlugManX.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[leaf-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[leaf-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1021) ~[leaf-1.20.4.jar:git-Leaf-"3669cb6"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchServerCommand(CraftServer.java:1006) ~[leaf-1.20.4.jar:git-Leaf-"3669cb6"]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:547) ~[leaf-1.20.4.jar:git-Leaf-"3669cb6"
]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:495) ~[leaf-1.20.4.jar:git-Leaf-"3669cb6"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1528) ~[leaf-1.20.4.jar:git-Leaf-"3669cb6"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[leaf-1.20.4.jar:git-Leaf-"3669cb6"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:306) ~[leaf-1.20.4.jar:git-Leaf-"3669cb6"]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by blank038** [comment]
可以通过在 AyCore 的 config.yml 中关闭 hikari 设定来使用原生连接而不走连接池。

**Comment by 404forever1** [comment]
> 可以通过在 AyCore 的 config.yml 中关闭 hikari 设定来使用原生连接而不走连接池。

已经测试，这个办法还是会导致插件无法加载。但是手动unload后load就加载上了，很奇怪

**Comment by blank038** [comment]
> > 可以通过在 AyCore 的 config.yml 中关闭 hikari 设定来使用原生连接而不走连接池。
> 
> 已经测试，这个办法还是会导致插件无法加载。但是手动unload后load就加载上了，很奇怪

或许可以将 ServerMarket、AyCore 的加载与启动日志都提取出来呢？我尝试能否复现。
https://paste.helpch.at/

**Comment by 404forever1** [comment]
https://paste.helpch.at/ihaluyipam.makefile
大概知道为什么以前可以正常运行了
我在测试端上，加载aycore加载hirk会报错应该是下载失败了。以前应该也是一直下载失败，但是突然成功了

**Comment by 404forever1** [comment]
> plugman unload NyEconomy
[17:49:37 INFO]: [PlugMan] NyEconomy has been unloaded.
[17:49:42 WARN]: [Topper] There is an error while parsing the placeholder for money
java.lang.NumberFormatException: For input string: "%nyeconomy_星海碎片%"
        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[?:?]
        at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
        at java.base/java.lang.Double.parseDouble(Double.java:792) ~[?:?]
        at topper-spigot-placeholder-leaderboard-2.6.0-shaded.jar/me.hsgamer.topper.placeholderleaderboard.holder.PlaceholderTopHolder.lambd
a$updateNewValue$0(PlaceholderTopHolder.java:55) ~[topper-spigot-placeholder-leaderboard-2.6.0-shaded.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:91) ~[leaf-1.20.4.jar:git-Leaf-"3669cb6"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:481) ~[leaf-1.20.4.jar:git-Leaf-
"3669cb6"]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1638) ~[leaf-1.20.4.jar:git-Leaf-"3669cb6"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:494) ~[leaf-1.20.4.jar:git-Leaf-"3669cb6"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1528) ~[leaf-1.20.4.jar:git-Leaf-"3669cb6"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[leaf-1.20.4.jar:git-Leaf-"3669cb6"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:306) ~[leaf-1.20.4.jar:git-Leaf-"3669cb6"]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
> plugman load NyEconomy-1.7.0-SNAPSHOT
[17:49:44 INFO]: [NyEconomy] Loading server plugin NyEconomy v1.7.0-SNAPSHOT
[17:49:44 INFO]: [NyEconomy] Enabling NyEconomy v1.7.0-SNAPSHOT
[17:49:44 INFO]: [com.zaxxer.hikari.HikariDataSource] NyEconomy-Pool - Starting...
[17:49:44 INFO]: [com.zaxxer.hikari.HikariDataSource] NyEconomy-Pool - Start completed.
[17:49:44 INFO]: [PlaceholderAPI] Successfully registered internal expansion: nyeconomy [1.7.0-SNAPSHOT]
[17:49:44 INFO]: [NyEconomy] ================================
[17:49:44 INFO]: [NyEconomy]  > 正在加载九域多经济系统...
[17:49:44 INFO]: [NyEconomy]  > 成功挂钩 PlaceholderAPI ✔
[17:49:44 INFO]: [NyEconomy]  > 未检测到 Vault 经济桥 ✘
[17:49:44 INFO]: [NyEconomy]  > HikariCP 状态: ✔ 
[17:49:44 INFO]: [NyEconomy]  > 开始加载经济货币项
[17:49:44 INFO]: [NyEconomy]   -> 成功加载货币项: 星海碎片
[17:49:44 INFO]: [NyEconomy]   -> 成功加载货币项: 星海晶石
[17:49:44 INFO]: [NyEconomy]  > 经济加载完成, 共加载 2 项
[17:49:44 INFO]: [NyEconomy]  > 开始加载商店物品项
[17:49:44 INFO]: [NyEconomy]  > 已加载商品 (成功[1] 失败[0])
[17:49:44 INFO]: [NyEconomy]  > 九域多经济系统加载完成
[17:49:44 INFO]: [NyEconomy] ================================
[17:49:44 INFO]: [PlugMan] NyEconomy has been loaded and enabled.
[17:49:48 INFO]: 玩家 541bc5f4-f86a-4401-962d-11d63e1fcb79, IP 223.94.196.121
[17:49:48 INFO]: UUID of player wwwekw is 541bc5f4-f86a-4401-962d-11d63e1fcb79
[17:49:48 INFO]: Base value for attribute Max Health for entity wwwekw set to 20.0
[17:49:48 INFO]: wwwekw[223.94.196.121/223.94.196.121:13690] logged in with entity id 294 at ([world]-549.0, 67.0, 42.0)
[17:49:49 INFO]: [SeeMore] Set view distance of wwwekw to 6 (client view distance is 8).
[17:49:51 INFO]: [FeatherMorph] wwwekw joined with API version 11
