### ISSUE TITLE
folia 好像无法正常加载，红的，热加载出现这个报错。

### ISSUE THREAD

**Issue by xiaoluofa** [blank038/ServerMarket#8]
正常加载也是红的
[18:13:36 INFO]: [PlugMan] ServerMarket has been unloaded.
> plugman load ServerMarket-2.6.0
[18:13:40 INFO]: [ServerMarket] Loading server plugin ServerMarket v2.6.0
[18:13:40 INFO]: [ServerMarket] Enabling ServerMarket v2.6.0
[18:13:40 INFO]:
[18:13:40 INFO]:    ServerMarket v2.6.0
[18:13:40 INFO]:
[18:13:40 ERROR]: Error occurred while enabling ServerMarket v2.6.0 (Is it up to date?)
java.lang.UnsupportedOperationException: null
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.handle(CraftScheduler.java:535) ~[luminol-1.20.4.jar:git-Luminol-"01abc6
c"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:259) ~[luminol-1.20.4.jar
:git-Luminol-"01abc6c"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:246) ~[luminol-1.20.4.jar
:git-Luminol-"01abc6c"]
        at com.aystudio.core.bukkit.util.mysql.MySqlStorageHandler.<init>(MySqlStorageHandler.java:38) ~[AyCore-1.0.6-BETA.jar:?]
        at com.blank038.servermarket.dto.impl.MysqlStorageHandlerImpl.initialize(MysqlStorageHandlerImpl.java:58) ~[ServerMarket-2.6.0.jar:?
]
        at com.blank038.servermarket.dto.AbstractStorageHandler.check(AbstractStorageHandler.java:41) ~[ServerMarket-2.6.0.jar:?]
        at com.blank038.servermarket.internal.plugin.ServerMarket.loadConfig(ServerMarket.java:87) ~[ServerMarket-2.6.0.jar:?]
        at com.blank038.servermarket.internal.plugin.ServerMarket.onEnable(ServerMarket.java:45) ~[ServerMarket-2.6.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[luminol-1.20.4.jar
:git-Luminol-"01abc6c"]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at com.rylinaux.plugman.util.PaperPluginUtil.load(PaperPluginUtil.java:421) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:116) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:97) ~[PlugManX.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1043) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchServerCommand(CraftServer.java:994) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c
"]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:505) ~[luminol-1.20.4.jar:git-Luminol-"01
abc6c"]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:296) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c
"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[luminol-1.20.4.jar
:git-Luminol-"01abc6c"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.
jar:git-Luminol-"01abc6c"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.j
ar:git-Luminol-"01abc6c"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[18:13:40 INFO]: [ServerMarket] Disabling ServerMarket v2.6.0

**Comment by xiaoluofa** [comment]
此外 NYE的变量在folia端也无法正常解析
![image](https://github.com/blank038/ServerMarket/assets/75927411/6917bce7-bfe7-4c10-b704-466576af1984)
使用了多服务器数据库同步
使用的是米饭改的placeholderapi

**Comment by blank038** [comment]
![{A3BB735E-CEC8-46a0-8039-E84E8C572F25}](https://github.com/blank038/ServerMarket/assets/30598468/8310b24b-877b-42a0-8bc6-8559607586b8)
![{929F2BF4-079E-4caa-A2C6-DAB19295887B}](https://github.com/blank038/ServerMarket/assets/30598468/2442657f-9bc9-4d68-ab00-af9ac6543ad6)

目前经过实测是没问题的，请通过正常启动服务器来加载插件而非热加载。

**Comment by xiaoluofa** [comment]
> ![{A3BB735E-CEC8-46a0-8039-E84E8C572F25}](https://private-user-images.githubusercontent.com/30598468/317820157-8310b24b-877b-42a0-8bc6-8559607586b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2ODY2NTIsIm5iZiI6MTcxMTY4NjM1MiwicGF0aCI6Ii8zMDU5ODQ2OC8zMTc4MjAxNTctODMxMGIyNGItODc3Yi00MmEwLThiYzYtODU1OTYwNzU4NmI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDA0MjU1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhYjg3ZWM1MzE4YzEyZjY0YmFhNTk0MWYyYWEyZjVjZGFiNzMxNjQ4M2U1YzY5MjlmOWYzMTBlN2M5YmJhNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gbk-rOqIG5t_iuGrg461dSIJxFkFJjECEwrGGaasPIs) ![{929F2BF4-079E-4caa-A2C6-DAB19295887B}](https://private-user-images.githubusercontent.com/30598468/317820546-2442657f-9bc9-4d68-ab00-af9ac6543ad6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2ODY2NTIsIm5iZiI6MTcxMTY4NjM1MiwicGF0aCI6Ii8zMDU5ODQ2OC8zMTc4MjA1NDYtMjQ0MjY1N2YtOWJjOS00ZDY4LWFiMDAtYWY5YWM2NTQzYWQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDA0MjU1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3NTgzZjI1NWI4ZDhkODZlYzZjZmU1YWRlNjZiZWEyMDFmZWRjMjVhNWU1YTdjMTVkNzAwNWNjYTExNTA0OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.37h6OXcyQs76cEKR62DJaerGXVOgKdtZE9biWG_ioeI)
> 
> 目前经过实测是没问题的，请通过正常启动服务器来加载插件而非热加载。

![image](https://github.com/blank038/ServerMarket/assets/75927411/0eb97c1e-e8a0-4ef2-a506-5c0602a1103f)
z正常启动的一个报错，是不是aycore的问题，我下载的版本不带folia support，我自己加的。

**Comment by xiaoluofa** [comment]
看来nye应该也是这个问题
数据库没连接上？

**Comment by blank038** [comment]
请下载 1.1.0-BETA 版本的 AyCore

https://cdn.mc9y.com/files/AyCore/AyCore-1.1.0-BETA.jar

**Comment by xiaoluofa** [comment]
解决
